openapi: 3.0.1
info:
  title: api
  version: 1.0.0
paths: {}
components:
  schemas:
    Result:
      type: object
      properties:
        matrix:
          $ref: "#/components/schemas/Matrix"

    Matrix:
      type: array
      items:
        $ref: "#/components/schemas/Row"

    Row:
      type: object
      properties:
        no:
          type: number
        desc:
          type: string
        figure:
          $ref: "#/components/schemas/Figure"

    Figure:
      allOf:
      - $ref: "#/components/schemas/FigureBase"
      - oneOf:
        - $ref: "#/components/schemas/Rect"
        - $ref: "#/components/schemas/Circle"

    FigureBase:
      type: object
      properties:
        name:
          type: string

    Point:
      type: object
      properties:
        x:
          type: number
        y:
          type: number

    Rect:
      type: object
      properties:
        pt1:
          $ref: "#/components/schemas/Point"
        pt2:
          $ref: "#/components/schemas/Point"

    Circle:
      type: object
      properties:
        center:
          $ref: "#/components/schemas/Point"
        radius:
          type: number

