openapi: 3.0.1
info:
  title: api
  version: 1.0.0
paths: {}
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    UserList:
      type: array
      items:
        $ref: "#/components/schemas/User"
    Group:
      type: object
      properties:
        users:
          $ref: "#/components/schemas/UserList"
        name:
          type: string
